In [ ]:
def convert_length(value, unit_from, unit_to):
    """
    Convert between meters and feet.

    Parameters:
    value (float): The value to be converted.
    unit_from (str): The unit to convert from ('m' or 'ft').
    unit_to (str): The unit to convert to ('m' or 'ft').

    Returns:
    float: The converted value.
    """
    if unit_from == 'm' and unit_to == 'ft':
        return value * 3.28084  # Meters to feet
    elif unit_from == 'ft' and unit_to == 'm':
        return value / 3.28084  # Feet to meters
    else:
        raise ValueError("Unsupported units for length conversion.")

def convert_weight(value, unit_from, unit_to):
    """
    Convert between kilograms and pounds.

    Parameters:
    value (float): The value to be converted.
    unit_from (str): The unit to convert from ('kg' or 'lbs').
    unit_to (str): The unit to convert to ('kg' or 'lbs').

    Returns:
    float: The converted value.
    """
    if unit_from == 'kg' and unit_to == 'lbs':
        return value * 2.20462  # Kilograms to pounds
    elif unit_from == 'lbs' and unit_to == 'kg':
        return value / 2.20462  # Pounds to kilograms
    else:
        raise ValueError("Unsupported units for weight conversion.")

def convert_volume(value, unit_from, unit_to):
    """
    Convert between liters and gallons.

    Parameters:
    value (float): The value to be converted.
    unit_from (str): The unit to convert from ('L' or 'gal').
    unit_to (str): The unit to convert to ('L' or 'gal').

    Returns:
    float: The converted value.
    """
    if unit_from == 'L' and unit_to == 'gal':
        return value * 0.264172  # Liters to gallons
    elif unit_from == 'gal' and unit_to == 'L':
        return value / 0.264172  # Gallons to liters
    else:
        raise ValueError("Unsupported units for volume conversion.")

def main():
    print("Welcome to the Unit Converter!")

    # Prompt user to choose conversion type
    conversion_type = input("Choose the conversion type (length, weight, volume): ").lower()

    if conversion_type not in ['length', 'weight', 'volume']:
        print("Invalid conversion type selected.")
        return

    try:
        # Prompt user to enter value
        value = float(input("Enter the value to be converted: "))

        if conversion_type == 'length':
            unit_from = input("Enter the unit to convert from (m or ft): ").lower()
            unit_to = input("Enter the unit to convert to (m or ft): ").lower()
            result = convert_length(value, unit_from, unit_to)

        elif conversion_type == 'weight':
            unit_from = input("Enter the unit to convert from (kg or lbs): ").lower()
            unit_to = input("Enter the unit to convert to (kg or lbs): ").lower()
            result = convert_weight(value, unit_from, unit_to)

        elif conversion_type == 'volume':
            unit_from = input("Enter the unit to convert from (L or gal): ").lower()
            unit_to = input("Enter the unit to convert to (L or gal): ").lower()
            result = convert_volume(value, unit_from, unit_to)

        print(f"Converted value: {result}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Welcome to the Unit Converter!
Choose the conversion type (length, weight, volume): weight
Enter the value to be converted: 12
Enter the unit to convert from (kg or lbs): kg
Enter the unit to convert to (kg or lbs): lbs
Converted value: 26.455439999999996


In [ ]:
a=[1,2,3,4,5,6,2,1,3]
result=[a[i] for i in range(len(a)) if i%2==0]
print(result)



[1, 3, 5, 2, 3]


In [ ]:
a=[1,2,3,4,5,6,2,1,3]
print(a[::2])

[1, 3, 5, 2, 3]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
print(a[::-1])


[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
def fisrt_and_last_gone(ok):
  out=ok[1:-1]
  print(out)

list=[1,2,3,4,5]
print(list)
fisrt_and_last_gone(list)



[1, 2, 3, 4, 5]
[2, 3, 4]


In [ ]:
def get_first_n(lst, n):
  print([lst[0:n]])
get_first_n([1,2,3,4,5,6,7],5 )

[[1, 2, 3, 4, 5]]


In [ ]:
def get_last_n(lst, n):
  print([lst[n:]])
get_last_n([1,2,3,4,5,6,7],2 )

[[3, 4, 5, 6, 7]]


4.3

  

In [ ]:
# <!-- For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].
#  -->
list= [[1, 2], [3, 4], [5]]
flatlist=[]
for i in list:
 for a in i:
   flatlist.append(a)
print(flatlist)

[1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
  for i in indices:
    lst=lst[i]
  return lst

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
i=[2,2]
access_nested_element(lst, i)



9

In [ ]:
def flat(lst):
    flat_list = []  # ✅ Define a local list to store flattened elements
    for i in lst:
      if isinstance(i, list):
        flat_list.extend(flat(i))  # Recursively flatten nested lists
      else:
        flat_list.append(i)  # Add non-list elements directly
    return flat_list  # ✅ Return the fully flattened list

lst = [[1, 2], [3, [4, 5]], 6]
flat_list = flat(lst)  # Call the function and store the result

print(flat_list)  # ✅ Output: [1, 2, 3, 4, 5, 6]
print(sum(flat_list))  # ✅ Output: 21



[1, 2, 3, 4, 5, 6]
21


In [ ]:
# – Define a function remove element(lst, elem) that removes elem from lst and returns the
# modified list.
# – Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
# be [[1], [3], [4, 5]].


def remove_element(lst, elem):
  for i in lst:
    while elem in i:
      i.remove(elem)
  return lst


lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem)
)

[[1], [3], [4, 5]]


In [ ]:
# Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

lst=[[1, 2], [3, [4, 5]], 6]

def flat(lst):
  flatten_list=[]
  for i in lst:
    if isinstance(i,list):
      flatten_list.extend(flat(i))
    else:
      flatten_list.append(i)
  return flatten_list

def find_max(lst):
  return max(lst)


a=flat(lst)
print(flat(lst))
find_max(a)

[1, 2, 3, 4, 5, 6]


6

In [ ]:
from itertools import count
# For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
# be 3.

lst= [[1, 2], [2, 3], [2, 4]]
elem=2
def flat_list(lst):
  flat_lst=[];
  for i in lst:
    flat_lst.extend(i)
  return flat_lst;

def reOccurence(lst,elem):
  num=lst.count(elem)
  return num


a=flat_list(lst)
print(a)
b=reOccurence(a,elem)

print(b)


[1, 2, 2, 3, 2, 4]
3


In [ ]:
# Define a function average nested(lst) that takes a nested list lst and returns the average
# of all the elements.
# – Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.


Numpy


In [ ]:
# Initialize an empty array with size 2X2.
import numpy as np

ok=np.empty((2,2))
print(ok)

[[1.97155616e-316 0.00000000e+000]
 [2.06491614e-316 6.89928648e-310]]


In [ ]:
# Initialize an all one array with size 4X2.
ok=np.ones((4,2))
print (ok)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
ok=np.full((2,4,4),9)
print(ok)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [ ]:
# Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
ok=np.full((4,3,4),8)
print(ok)
allZero=np.zeros_like(ok)
print(allZero)

[[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
ok=np.full((1,2,3),0)
new=np.ones_like(ok)
print(new)

[[[1 1 1]
  [1 1 1]]]


In [ ]:
# For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
nparr=np.array(new_list)

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:



In [ ]:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
ok=np.arange(10,50)
print(ok)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
ok=np.arange(0,9).reshape(3,3)
print(ok)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Create a 3X3 identity matrix.{Hint:np.eye()}
ok=np.eye(3)
print(ok)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a random array of size 30 and find the mean of the array.
ok = np.random.randint(0, 50, 30)

mean_value = np.mean(ok)

print("Array:", ok)
print("Mean:", mean_value)

Array: [11  1 12 37 49 44 46 37 29  8 47  4 21 34 11 12 47 31 36 11 11 14  3 25
 48 21 25 26 46 27]
Mean: 25.8


In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
ok=np.random.randint(0,1000,(10,10))
print(ok)
min=np.min(ok)
max=np.max(ok)
print(min)
print(max)

[[899 816 195 971 152 498 655 107 314 818]
 [171 859   2 329 819 958 555 401 609 273]
 [971 834 253 108 273 285 903 500 515 526]
 [332 200 294 765 544 512 993 352 492 706]
 [551 407  80 280 625 318 957 765 913 918]
 [826 540 953 150 706 153 107 879 640 184]
 [ 54 304 948 727 502 772 874 454 599 812]
 [807 461 992  37 795 875 822 623  17 421]
 [754 874 366 181 456 823 575 824 584 659]
 [856 634 882 875 228 706 733 736 903 684]]
2
993


In [ ]:
# Create a zero array of size 10 and replace 5th element with 1.
ok=np.zeros(10)
print(ok)
ok[5]=1
print(ok)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
# Reverse an array arr = [1,2,0,0,4,0].
arr =np.array([1,2,0,0,4,0])
RevArr=arr[::-1]
print(arr)
print(RevArr)


[1 2 0 0 4 0]
[0 4 0 0 2 1]


In [ ]:
# Create a 2d array with 1 on border and 0 inside.
ok=np.zeros((3,3))
print(ok)
ok[0,:]=1
ok[:,0]=1
ok[-1,:]=1
ok[:,-1]=1

print(ok)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [ ]:
# Create a 8X8 matrix and fill it with a checkerboard pattern.
ok=np.zeros((8,8))
ok[::2,::2]=1
print(ok)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Problem - 3: Array Operations:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
# 2. Subtract the two array.
# 3. Multiply the array with any integers of your choice.
# 4. Find the square of each element of the array.
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9, 10])
w = np.array([11, 12])
# add=np.add(x,y)
# subtract=np.subtract(x,y)
# print(add)
# print(subtract)
# mul=np.multiply(x,y)
# print(mul)
# sqX=np.square(x)
# print(sqX)
# sqY=np.square(y)
# print(sqY)
# dot_vw = np.dot(v, w)
# dot_xv = np.dot(x, v)
# dot_xy = np.dot(x, y)

# print(dot_vw)
# print(dot_xv)
# print(dot_xy)

concatenate_xy = np.concatenate((x, y), axis=0)  # Concatenate x and y along rows
concatenate_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Concatenate v and w along columns

print(concatenate_xy)
print(concatenate_vw)




[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


MAtrix

In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant matrix B
B = np.array([-1, -3, 9])
A_inv=np.linalg.inv(A)
print(A)
X=np.dot(A_inv,B)
print(X)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
[ 2.  1. -2.]


In [ ]:
# • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ̸= BA.
# 3. Prove (AB)

# T = BTAT
# .
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
c=np.dot(A,A_inv)
print(c)
AB=np.dot(A,B)
BA=np.dot(A,B)
print(AB)
print(BA)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[23 13]
 [51 29]]


In [ ]:
import time
import numpy as np


In [ ]:
# Create two lists with size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure time for element-wise addition using Python lists
start_time = time.time()

# Perform element-wise addition
result = [list1[i] + list2[i] for i in range(1000000)]

end_time = time.time()
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")


Time taken for element-wise addition using Python lists: 0.11552786827087402 seconds


In [ ]:
# Create two NumPy arrays with size 1,000,000
array1 = np.arange(1000000)
array2 = np.arange(1000000)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()

# Perform element-wise addition
result = array1 + array2

end_time = time.time()
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using NumPy arrays: 0.0030808448791503906 seconds


In [ ]:
# Measure time for element-wise multiplication using Python lists
start_time = time.time()

# Perform element-wise multiplication
result = [list1[i] * list2[i] for i in range(1000000)]

end_time = time.time()
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python lists: 0.07611989974975586 seconds


In [ ]:
# Measure time for element-wise multiplication using NumPy arrays
start_time = time.time()

# Perform element-wise multiplication
result = array1 * array2

end_time = time.time()
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.003176450729370117 seconds


In [ ]:
# Measure time for dot product using Python lists
start_time = time.time()

# Compute dot product
dot_product = sum(list1[i] * list2[i] for i in range(1000000))

end_time = time.time()
print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.09728264808654785 seconds


In [ ]:
# Measure time for dot product using NumPy arrays
start_time = time.time()

# Compute dot product
dot_product = np.dot(array1, array2)

end_time = time.time()
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time} seconds")


Time taken for dot product using NumPy arrays: 0.006998300552368164 seconds
